# -*- coding: utf-8 -*-
"""Generate migrations/2026-08-11b-invoicing-seed.sql from the offline invoicing data
(D:\\opencode\\invoices) so it can be run in pgAdmin4 / psql against the SaaS database.

The output upserts (INSERT ... ON CONFLICT DO UPDATE) so re-running is harmless, and the
current SaaS database always reflects the offline source of truth.

Usage:
    python scripts/build_invoice_seed_sql.py [--invoices D:\\opencode\\invoices] [-o out.sql]
"""
import argparse
import json
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
BACKEND_DIR = os.path.dirname(SCRIPT_DIR)


def esc(text) -> str:
    """Escape a Python string for a Postgres single-quoted literal."""
    return str(text).replace("'", "''")


def jsonb(data) -> str:
    """Render JSON data as a Postgres '...'::jsonb literal."""
    return "'" + json.dumps(data, ensure_ascii=False).replace("'", "''") + "'::jsonb"


def text_lit(value) -> str:
    if value is None:
        return "NULL"
    return "'" + esc(value) + "'"


def num_lit(value, default=0) -> str:
    if value is None:
        return str(default)
    return repr(round(float(value), 2))


def bool_lit(value, default=False) -> str:
    if value is None:
        return "TRUE" if default else "FALSE"
    return "TRUE" if value else "FALSE"


def header() -> str:
    return ("-- Generated by scripts/build_invoice_seed_sql.py from D:\\opencode\\invoices.\n"
            "-- Regenerate with `python scripts/build_invoice_seed_sql.py` whenever the offline\n"
            "-- data changes; every statement upserts, so re-running is harmless.\n"
            "-- Run AFTER 2026-08-11a-invoicing.sql (tables must exist).\n\n")


def seller_sql(root) -> str:
    path = os.path.join(root, "master", "seller.json")
    if not os.path.exists(path):
        return ""
    with open(path, "r", encoding="utf-8-sig") as f:
        s = json.load(f)
    bank = jsonb(s.get("bank", {}))
    rates = jsonb(s.get("gst_rates", {}))
    lines = [
        "INSERT INTO invoice_seller (id, name, entity_type, llpin, pan, registered_office, state,",
        "    state_code, email, phone, gst_registered, gst_levied, gstin, arn,",
        "    registration_application_date, gst_rates, bank, jurisdiction)",
        "VALUES (1,",
        f"    {text_lit(s.get('name'))}, {text_lit(s.get('entity_type'))}, {text_lit(s.get('llpin'))},",
        f"    {text_lit(s.get('pan'))}, {text_lit(s.get('registered_office'))}, {text_lit(s.get('state'))},",
        f"    {text_lit(s.get('state_code'))}, {text_lit(s.get('email'))}, {text_lit(s.get('phone'))},",
        f"    {bool_lit(s.get('gst_registered'))}, {bool_lit(s.get('gst_levied'))}, {text_lit(s.get('gstin'))},",
        f"    {text_lit(s.get('arn'))}, {text_lit(s.get('registration_application_date'))},",
        f"    {rates}, {bank}, {text_lit(s.get('jurisdiction'))})",
        "ON CONFLICT (id) DO UPDATE SET",
        "    name = EXCLUDED.name, entity_type = EXCLUDED.entity_type, llpin = EXCLUDED.llpin,",
        "    pan = EXCLUDED.pan, registered_office = EXCLUDED.registered_office, state = EXCLUDED.state,",
        "    state_code = EXCLUDED.state_code, email = EXCLUDED.email, phone = EXCLUDED.phone,",
        "    gst_registered = EXCLUDED.gst_registered, gst_levied = EXCLUDED.gst_levied,",
        "    gstin = EXCLUDED.gstin, arn = EXCLUDED.arn,",
        "    registration_application_date = EXCLUDED.registration_application_date,",
        "    gst_rates = EXCLUDED.gst_rates, bank = EXCLUDED.bank, jurisdiction = EXCLUDED.jurisdiction;",
        "",
    ]
    return "\n".join(lines) + "\n"


def buyers_sql(root) -> str:
    path = os.path.join(root, "master", "buyers.json")
    if not os.path.exists(path):
        return ""
    with open(path, "r", encoding="utf-8-sig") as f:
        buyers = json.load(f)
    out = []
    for key, b in buyers.items():
        out.append("INSERT INTO invoice_buyers (key, name, billing_address, delivery_address, state,")
        out.append("    state_code, gstin, contact_name, contact_email, contact_phone)")
        out.append("VALUES (" + text_lit(key) + ",")
        out.append(f"    {text_lit(b.get('name'))}, {text_lit(b.get('billing_address'))}, {text_lit(b.get('delivery_address'))},")
        out.append(f"    {text_lit(b.get('state'))}, {text_lit(b.get('state_code'))}, {text_lit(b.get('gstin'))},")
        out.append(f"    {text_lit(b.get('contact_name'))}, {text_lit(b.get('contact_email'))}, {text_lit(b.get('contact_phone'))})")
        out.append("ON CONFLICT (key) DO UPDATE SET")
        out.append("    name = EXCLUDED.name, billing_address = EXCLUDED.billing_address,")
        out.append("    delivery_address = EXCLUDED.delivery_address, state = EXCLUDED.state,")
        out.append("    state_code = EXCLUDED.state_code, gstin = EXCLUDED.gstin,")
        out.append("    contact_name = EXCLUDED.contact_name, contact_email = EXCLUDED.contact_email,")
        out.append("    contact_phone = EXCLUDED.contact_phone;")
        out.append("")
    return "\n".join(out) + "\n"


def register_sql(root) -> str:
    path = os.path.join(root, "registers", "invoice-register.json")
    if not os.path.exists(path):
        return ""
    with open(path, "r", encoding="utf-8-sig") as f:
        reg = json.load(f)
    out = []
    fy = reg.get("fy", "")
    for kind, series in (reg.get("series") or {}).items():
        if isinstance(series, dict) and "last_seq" in series:
            series = {"": series}
        for tag, st in (series or {}).items():
            seq = st["last_seq"] if isinstance(st, dict) else st
            out.append("INSERT INTO invoice_register (fy, kind, tag, last_seq)")
            out.append(f"VALUES ({text_lit(fy)}, {text_lit(kind)}, {text_lit(tag)}, {int(seq)})")
            out.append("ON CONFLICT (fy, kind, tag) DO UPDATE SET last_seq = EXCLUDED.last_seq;")
            out.append("")
    return "\n".join(out) + "\n"


def orders_sql(root) -> str:
    orders_dir = os.path.join(root, "orders")
    if not os.path.isdir(orders_dir):
        return ""
    files = sorted(f for f in os.listdir(orders_dir) if f.endswith(".json") and not f.startswith("_"))
    out = []
    for fn in files:
        with open(os.path.join(orders_dir, fn), "r", encoding="utf-8-sig") as f:
            o = json.load(f)
        out.append("INSERT INTO invoice_orders (po_no, po_date, buyer, account, goods, state, items,")
        out.append("    milestones, payments, invoices, freight, freight_in_rate, discount, items_value,")
        out.append("    contract_value, advances_received, cumulative_billed, shipping_address,")
        out.append("    shipping_state_code, place_of_supply, payment_terms, delivery_terms, validity,")
        out.append("    remarks, e_way_bill, gst_collectable)")
        out.append("VALUES (")
        out.append(f"    {text_lit(o.get('po_no'))}, {text_lit(o.get('po_date'))}, {text_lit(o.get('buyer'))},")
        out.append(f"    {text_lit(o.get('account'))}, {bool_lit(o.get('goods'), True)}, {text_lit(o.get('state'))},")
        out.append(f"    {jsonb(o.get('items', []))}, {jsonb(o.get('milestones', []))},")
        out.append(f"    {jsonb(o.get('payments', []))}, {jsonb(o.get('invoices', []))},")
        out.append(f"    {num_lit(o.get('freight'))}, {bool_lit(o.get('freight_in_rate'))}, {num_lit(o.get('discount'))},")
        out.append(f"    {num_lit(o.get('items_value'))}, {num_lit(o.get('contract_value'))},")
        out.append(f"    {num_lit(o.get('advances_received'))}, {num_lit(o.get('cumulative_billed'))},")
        out.append(f"    {jsonb(o['shipping_address']) if o.get('shipping_address') else 'NULL'},")
        out.append(f"    {text_lit(o.get('shipping_state_code'))}, {text_lit(o.get('place_of_supply'))},")
        out.append(f"    {text_lit(o.get('payment_terms'))}, {text_lit(o.get('delivery_terms'))},")
        out.append(f"    {text_lit(o.get('validity'))}, {text_lit(o.get('remarks'))},")
        out.append(f"    {jsonb(o['e_way_bill']) if o.get('e_way_bill') else 'NULL'},")
        out.append(f"    {bool_lit(o.get('gst_collectable')) if o.get('gst_collectable') is not None else 'NULL'})")
        out.append("ON CONFLICT (po_no) DO UPDATE SET")
        out.append("    po_date = EXCLUDED.po_date, buyer = EXCLUDED.buyer, account = EXCLUDED.account,")
        out.append("    goods = EXCLUDED.goods, state = EXCLUDED.state, items = EXCLUDED.items,")
        out.append("    milestones = EXCLUDED.milestones, payments = EXCLUDED.payments,")
        out.append("    invoices = EXCLUDED.invoices, freight = EXCLUDED.freight,")
        out.append("    freight_in_rate = EXCLUDED.freight_in_rate, discount = EXCLUDED.discount,")
        out.append("    items_value = EXCLUDED.items_value, contract_value = EXCLUDED.contract_value,")
        out.append("    advances_received = EXCLUDED.advances_received,")
        out.append("    cumulative_billed = EXCLUDED.cumulative_billed,")
        out.append("    shipping_address = EXCLUDED.shipping_address,")
        out.append("    shipping_state_code = EXCLUDED.shipping_state_code,")
        out.append("    place_of_supply = EXCLUDED.place_of_supply,")
        out.append("    payment_terms = EXCLUDED.payment_terms, delivery_terms = EXCLUDED.delivery_terms,")
        out.append("    validity = EXCLUDED.validity, remarks = EXCLUDED.remarks,")
        out.append("    e_way_bill = EXCLUDED.e_way_bill, gst_collectable = EXCLUDED.gst_collectable;")
        out.append("")
    return "\n".join(out) + "\n"


def transactions_sql(root) -> str:
    path = os.path.join(root, "master", "transactions.json")
    if not os.path.exists(path):
        return ""
    with open(path, "r", encoding="utf-8-sig") as f:
        data = json.load(f)
    out = []
    for t in data.get("transactions", []):
        out.append("INSERT INTO invoice_transactions (s_no, date, amount, remarks, bank_ref,")
        out.append("    allocations, combined_invoice)")
        out.append("VALUES (")
        out.append(f"    {int(t['s_no'])}, {text_lit(t.get('date'))}, {num_lit(t.get('amount'))},")
        out.append(f"    {text_lit(t.get('remarks'))}, {text_lit(t.get('bank_ref'))},")
        out.append(f"    {jsonb(t.get('allocations', []))}, {text_lit(t.get('combined_invoice'))})")
        out.append("ON CONFLICT (s_no) DO UPDATE SET")
        out.append("    date = EXCLUDED.date, amount = EXCLUDED.amount, remarks = EXCLUDED.remarks,")
        out.append("    bank_ref = EXCLUDED.bank_ref, allocations = EXCLUDED.allocations,")
        out.append("    combined_invoice = EXCLUDED.combined_invoice;")
        out.append("")
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--invoices", default=os.path.normpath(os.path.join(BACKEND_DIR, "..", "..", "..", "invoices")),
                    help="path to the offline invoices/ folder")
    ap.add_argument("-o", "--out", default=os.path.join(BACKEND_DIR, "migrations", "2026-08-11b-invoicing-seed.sql"))
    args = ap.parse_args()

    root = os.path.abspath(args.invoices)
    if not os.path.isdir(root):
        sys.exit(f"Invoices folder not found: {root}")

    sql = header()
    sql += seller_sql(root)
    sql += buyers_sql(root)
    sql += register_sql(root)
    sql += orders_sql(root)
    sql += transactions_sql(root)

    with open(args.out, "w", encoding="utf-8") as f:
        f.write(sql)
    print(f"Wrote {args.out} ({len(sql.splitlines())} lines, source: {root})")


if __name__ == "__main__":
    main()
