-- Generated by scripts/build_invoice_seed_sql.py from D:\opencode\invoices.
-- Regenerate with `python scripts/build_invoice_seed_sql.py` whenever the offline
-- data changes; every statement upserts, so re-running is harmless.
-- Run AFTER 2026-08-11a-invoicing.sql (tables must exist).

INSERT INTO invoice_seller (id, name, entity_type, llpin, pan, registered_office, state,
    state_code, email, phone, gst_registered, gst_levied, gstin, arn,
    registration_application_date, gst_rates, bank, jurisdiction)
VALUES (1,
    'Aracharat Ventures LLP', 'Limited Liability Partnership', 'ACZ-3057',
    'ACOFA8793J', '56, Green View 2, A to Z Colony, Modipuram, Meerut, Uttar Pradesh - 250110', 'Uttar Pradesh',
    '09', 'corporate@aracharatventures.com', '+91 98211 63135',
    TRUE, FALSE, '09ACOFA8793J1ZH',
    'AA090726172861R', '2026-07-20',
    '{"cgst": 9.0, "sgst": 9.0, "igst": 18.0}'::jsonb, '{"bank_name": "ICICI Bank", "account_name": "Akash Rathi", "account_number": "032101647907", "ifsc": "ICIC0000321", "note": "Personal account in use for now - swap to LLP current account once available."}'::jsonb, 'Meerut, Uttar Pradesh')
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name, entity_type = EXCLUDED.entity_type, llpin = EXCLUDED.llpin,
    pan = EXCLUDED.pan, registered_office = EXCLUDED.registered_office, state = EXCLUDED.state,
    state_code = EXCLUDED.state_code, email = EXCLUDED.email, phone = EXCLUDED.phone,
    gst_registered = EXCLUDED.gst_registered, gst_levied = EXCLUDED.gst_levied,
    gstin = EXCLUDED.gstin, arn = EXCLUDED.arn,
    registration_application_date = EXCLUDED.registration_application_date,
    gst_rates = EXCLUDED.gst_rates, bank = EXCLUDED.bank, jurisdiction = EXCLUDED.jurisdiction;

INSERT INTO invoice_buyers (key, name, billing_address, delivery_address, state,
    state_code, gstin, contact_name, contact_email, contact_phone)
VALUES ('LCB',
    'LCB Fertilizers Pvt. Ltd.', 'H. No. 657/X, Shyam Vihar Phase 2, Rani Sati Mandir Road, Gorakhpur, Uttar Pradesh - 273015', 'H. No. 657/X, Shyam Vihar Phase 2, Rani Sati Mandir Road, Gorakhpur, Uttar Pradesh - 273015',
    'Uttar Pradesh', '09', '09AAECL1674Q1ZU',
    'Akshay', 'contact@lcbfertilizers.in', '+91 79059 87520')
ON CONFLICT (key) DO UPDATE SET
    name = EXCLUDED.name, billing_address = EXCLUDED.billing_address,
    delivery_address = EXCLUDED.delivery_address, state = EXCLUDED.state,
    state_code = EXCLUDED.state_code, gstin = EXCLUDED.gstin,
    contact_name = EXCLUDED.contact_name, contact_email = EXCLUDED.contact_email,
    contact_phone = EXCLUDED.contact_phone;

INSERT INTO invoice_register (fy, kind, tag, last_seq)
VALUES ('26-27', 'PO', 'SH', 5)
ON CONFLICT (fy, kind, tag) DO UPDATE SET last_seq = EXCLUDED.last_seq;

INSERT INTO invoice_register (fy, kind, tag, last_seq)
VALUES ('26-27', 'PO', 'FER', 1)
ON CONFLICT (fy, kind, tag) DO UPDATE SET last_seq = EXCLUDED.last_seq;

INSERT INTO invoice_register (fy, kind, tag, last_seq)
VALUES ('26-27', 'INV', 'SH', 14)
ON CONFLICT (fy, kind, tag) DO UPDATE SET last_seq = EXCLUDED.last_seq;

INSERT INTO invoice_register (fy, kind, tag, last_seq)
VALUES ('26-27', 'INV', 'FER', 5)
ON CONFLICT (fy, kind, tag) DO UPDATE SET last_seq = EXCLUDED.last_seq;

INSERT INTO invoice_register (fy, kind, tag, last_seq)
VALUES ('26-27', 'CN', '', 0)
ON CONFLICT (fy, kind, tag) DO UPDATE SET last_seq = EXCLUDED.last_seq;

INSERT INTO invoice_register (fy, kind, tag, last_seq)
VALUES ('26-27', 'DN', '', 0)
ON CONFLICT (fy, kind, tag) DO UPDATE SET last_seq = EXCLUDED.last_seq;

INSERT INTO invoice_register (fy, kind, tag, last_seq)
VALUES ('26-27', 'RV', 'SH', 5)
ON CONFLICT (fy, kind, tag) DO UPDATE SET last_seq = EXCLUDED.last_seq;

INSERT INTO invoice_register (fy, kind, tag, last_seq)
VALUES ('26-27', 'RV', 'FER', 1)
ON CONFLICT (fy, kind, tag) DO UPDATE SET last_seq = EXCLUDED.last_seq;

INSERT INTO invoice_register (fy, kind, tag, last_seq)
VALUES ('26-27', 'CMB', '', 5)
ON CONFLICT (fy, kind, tag) DO UPDATE SET last_seq = EXCLUDED.last_seq;

INSERT INTO invoice_orders (po_no, po_date, buyer, account, goods, state, items,
    milestones, payments, invoices, freight, freight_in_rate, discount, items_value,
    contract_value, advances_received, cumulative_billed, shipping_address,
    shipping_state_code, place_of_supply, payment_terms, delivery_terms, validity,
    remarks, e_way_bill, gst_collectable)
VALUES (
    'AVL-PO/26-27/FER/001', '2026-07-09', 'LCB',
    'fertilizer', TRUE, 'PARTIAL-BILLED',
    '[{"description": "Navyakosh Organic Microbial Fertilizer", "specs": "Freight included in rate. Supply as per LCB schedule.", "hsn": "3101 00 00", "qty": 26.5, "uqc": "MT", "rate": 12000.0}]'::jsonb, '[{"label": "Partial payment F1", "percent": 16, "trigger": "Paid 20/06/2026"}, {"label": "Partial payment F2", "percent": 31, "trigger": "Paid 09/07/2026"}, {"label": "Partial payment F3", "percent": 16, "trigger": "Paid 15/07/2026"}, {"label": "Partial payment F4", "percent": 16, "trigger": "Paid 16/07/2026"}, {"label": "Balance on delivery", "percent": 21, "trigger": "On delivery"}]'::jsonb,
    '[{"date": "2026-06-20", "amount": 50000.0, "mode": "NEFT", "remark": "Fertilizer first payment (F1) - transport advance", "invoice_no": "AVL/26-27/FER/001"}, {"date": "2026-07-09", "amount": 100000.0, "mode": "NEFT", "remark": "Fertilizer partial payment (F2)", "invoice_no": "AVL/26-27/FER/002"}, {"date": "2026-07-15", "amount": 50000.0, "mode": "NEFT", "remark": "Fertilizer partial payment (F3)", "invoice_no": "AVL/26-27/FER/003"}, {"date": "2026-07-16", "amount": 50000.0, "mode": "NEFT", "remark": "Fertilizer partial payment (F4) - Ashutosh", "invoice_no": "AVL/26-27/FER/004"}, {"date": "2026-08-11", "amount": 3500.0, "mode": "NEFT", "remark": "Fertilizer partial payment (F5) - balance of 30,000 receipt", "invoice_no": "AVL/26-27/FER/005"}]'::jsonb, '[{"kind": "ADVANCE", "no": "AVL/26-27/FER/001", "date": "2026-06-20", "amount": 50000.0, "mode": "NEFT", "remark": "Fertilizer first payment (F1) - transport advance"}, {"kind": "PARTIAL", "no": "AVL/26-27/FER/002", "date": "2026-07-09", "amount": 100000.0, "mode": "NEFT", "remark": "Fertilizer partial payment (F2)"}, {"kind": "PARTIAL", "no": "AVL/26-27/FER/003", "date": "2026-07-15", "amount": 50000.0, "mode": "NEFT", "remark": "Fertilizer partial payment (F3)"}, {"kind": "PARTIAL", "no": "AVL/26-27/FER/004", "date": "2026-07-16", "amount": 50000.0, "mode": "NEFT", "remark": "Fertilizer partial payment (F4) - Ashutosh"}, {"kind": "REVISED", "no": "AVL-RV/26-27/FER/001", "date": "2026-08-11", "amount": 318000.0, "remark": "Revised tax invoice replacing AVL/26-27/FER/004"}, {"kind": "PARTIAL", "no": "AVL/26-27/FER/005", "date": "2026-08-11", "amount": 3500.0, "mode": "NEFT", "remark": "Fertilizer partial payment (F5) - balance of 30,000 receipt"}]'::jsonb,
    0.0, TRUE, 0.0,
    318000.0, 318000.0,
    253500.0, 253500.0,
    '["GMR", "Odisha"]'::jsonb,
    '21', 'Odisha (21)',
    'Partial payments as per delivery schedule.', 'Dispatch as per LCB schedule.',
    'PO valid for 30 days.', 'Fertilizer order - 26.5 MT Navyakosh Organic Microbial Fertilizer @ INR 12/kg = INR 3,18,000 (freight included, 0% GST). Received INR 2,50,000 in four payments (F1: 20/06, F2: 09/07, F3: 15/07, F4: 16/07); balance INR 68,000 due on delivery.',
    NULL,
    FALSE)
ON CONFLICT (po_no) DO UPDATE SET
    po_date = EXCLUDED.po_date, buyer = EXCLUDED.buyer, account = EXCLUDED.account,
    goods = EXCLUDED.goods, state = EXCLUDED.state, items = EXCLUDED.items,
    milestones = EXCLUDED.milestones, payments = EXCLUDED.payments,
    invoices = EXCLUDED.invoices, freight = EXCLUDED.freight,
    freight_in_rate = EXCLUDED.freight_in_rate, discount = EXCLUDED.discount,
    items_value = EXCLUDED.items_value, contract_value = EXCLUDED.contract_value,
    advances_received = EXCLUDED.advances_received,
    cumulative_billed = EXCLUDED.cumulative_billed,
    shipping_address = EXCLUDED.shipping_address,
    shipping_state_code = EXCLUDED.shipping_state_code,
    place_of_supply = EXCLUDED.place_of_supply,
    payment_terms = EXCLUDED.payment_terms, delivery_terms = EXCLUDED.delivery_terms,
    validity = EXCLUDED.validity, remarks = EXCLUDED.remarks,
    e_way_bill = EXCLUDED.e_way_bill, gst_collectable = EXCLUDED.gst_collectable;

INSERT INTO invoice_orders (po_no, po_date, buyer, account, goods, state, items,
    milestones, payments, invoices, freight, freight_in_rate, discount, items_value,
    contract_value, advances_received, cumulative_billed, shipping_address,
    shipping_state_code, place_of_supply, payment_terms, delivery_terms, validity,
    remarks, e_way_bill, gst_collectable)
VALUES (
    'AVL-PO/26-27/SH/001', '2026-05-13', 'LCB',
    'hardware', TRUE, 'SETTLED',
    '[{"description": "IoT Hardware - Microcontroller Sensor Panels", "specs": "ESP32-S3 custom telemetry hardware unit with integrated sensor array and enclosure casing.", "hsn": "8517 62 90", "qty": 8, "uqc": "Nos", "rate": 7000.0}]'::jsonb, '[{"label": "Advance on PO acceptance", "percent": 49, "trigger": "On PO acceptance"}, {"label": "Balance on delivery", "percent": 51, "trigger": "On delivery"}]'::jsonb,
    '[{"date": "2026-05-13", "amount": 27500.0, "mode": "NEFT", "remark": "Advance payment for 8 sensors - order 1", "invoice_no": "AVL/26-27/SH/001"}, {"date": "2026-06-17", "amount": 28500.0, "mode": "NEFT", "remark": "Balance payment for 8 sensors - order 1", "invoice_no": "AVL/26-27/SH/003"}]'::jsonb, '[{"kind": "ADVANCE", "no": "AVL/26-27/SH/001", "date": "2026-05-13", "amount": 27500.0, "mode": "NEFT", "remark": "Advance payment for 8 sensors - order 1"}, {"kind": "PARTIAL", "no": "AVL/26-27/SH/003", "date": "2026-06-17", "amount": 28500.0, "mode": "NEFT", "remark": "Balance payment for 8 sensors - order 1"}, {"kind": "FINAL", "no": "AVL/26-27/SH/004", "date": "2026-06-17", "amount": 56000.0, "remark": "Final dispatch/settlement"}, {"kind": "REVISED", "no": "AVL-RV/26-27/SH/001", "date": "2026-08-11", "amount": 56000.0, "remark": "Revised tax invoice replacing AVL/26-27/SH/004"}]'::jsonb,
    0.0, FALSE, 0.0,
    56000.0, 56000.0,
    56000.0, 56000.0,
    '["BioSanjeevni", "Kamdhenu Dham Gaushala, Gurugram", "Haryana"]'::jsonb,
    '06', 'Haryana (06)',
    'Advance on PO acceptance; balance on delivery.', 'Sensors dispatched after advance receipt.',
    'PO valid for 30 days.', 'Order 1 - 8 ESP32-S3 sensor panels. Fully paid via two receipts (13/05/2026 and 17/06/2026).',
    '{"required": true, "generated_by": "buyer"}'::jsonb,
    NULL)
ON CONFLICT (po_no) DO UPDATE SET
    po_date = EXCLUDED.po_date, buyer = EXCLUDED.buyer, account = EXCLUDED.account,
    goods = EXCLUDED.goods, state = EXCLUDED.state, items = EXCLUDED.items,
    milestones = EXCLUDED.milestones, payments = EXCLUDED.payments,
    invoices = EXCLUDED.invoices, freight = EXCLUDED.freight,
    freight_in_rate = EXCLUDED.freight_in_rate, discount = EXCLUDED.discount,
    items_value = EXCLUDED.items_value, contract_value = EXCLUDED.contract_value,
    advances_received = EXCLUDED.advances_received,
    cumulative_billed = EXCLUDED.cumulative_billed,
    shipping_address = EXCLUDED.shipping_address,
    shipping_state_code = EXCLUDED.shipping_state_code,
    place_of_supply = EXCLUDED.place_of_supply,
    payment_terms = EXCLUDED.payment_terms, delivery_terms = EXCLUDED.delivery_terms,
    validity = EXCLUDED.validity, remarks = EXCLUDED.remarks,
    e_way_bill = EXCLUDED.e_way_bill, gst_collectable = EXCLUDED.gst_collectable;

INSERT INTO invoice_orders (po_no, po_date, buyer, account, goods, state, items,
    milestones, payments, invoices, freight, freight_in_rate, discount, items_value,
    contract_value, advances_received, cumulative_billed, shipping_address,
    shipping_state_code, place_of_supply, payment_terms, delivery_terms, validity,
    remarks, e_way_bill, gst_collectable)
VALUES (
    'AVL-PO/26-27/SH/002', '2026-05-13', 'LCB',
    'freight', FALSE, 'SETTLED',
    '[{"description": "Transportation / Freight - LCB Fertilizers sensor consignment (8 sensors)", "specs": "Pass-through freight reimbursement at actuals.", "qty": 1, "uqc": "Lot", "rate": 10500.0}]'::jsonb, '[{"label": "Transportation cost", "percent": 100, "trigger": "Paid 13/05/2026"}]'::jsonb,
    '[{"date": "2026-05-13", "amount": 10500.0, "mode": "NEFT", "remark": "Transportation cost", "invoice_no": "AVL/26-27/SH/002"}]'::jsonb, '[{"kind": "ADVANCE", "no": "AVL/26-27/SH/002", "date": "2026-05-13", "amount": 10500.0, "mode": "NEFT", "remark": "Transportation cost"}, {"kind": "CANCELLED", "no": "AVL/26-27/SH/006", "date": "2026-06-20", "amount": 0.0, "remark": "Cancelled - allocation reclassified to fertilizer order F1 (AVL/26-27/FER/001)"}, {"kind": "REVISED", "no": "AVL-RV/26-27/SH/005", "date": "2026-08-11", "amount": 10500.0, "remark": "Revised tax invoice replacing AVL/26-27/SH/002"}]'::jsonb,
    0.0, FALSE, 0.0,
    10500.0, 10500.0,
    10500.0, 10500.0,
    NULL,
    NULL, NULL,
    'Reimbursement at actuals.', 'As per dispatch schedule.',
    'PO valid for 30 days.', 'Freight / logistics account - INR 10,500 received from LCB on 13/05/2026 for transportation of the first 8 sensors (Order AVL-PO/26-27/SH/001). The earlier INR 50,000 (20/06/2026) was reclassified as fertilizer first payment F1 on Order AVL-PO/26-27/FER/001.',
    '{"required": false, "generated_by": "supplier"}'::jsonb,
    FALSE)
ON CONFLICT (po_no) DO UPDATE SET
    po_date = EXCLUDED.po_date, buyer = EXCLUDED.buyer, account = EXCLUDED.account,
    goods = EXCLUDED.goods, state = EXCLUDED.state, items = EXCLUDED.items,
    milestones = EXCLUDED.milestones, payments = EXCLUDED.payments,
    invoices = EXCLUDED.invoices, freight = EXCLUDED.freight,
    freight_in_rate = EXCLUDED.freight_in_rate, discount = EXCLUDED.discount,
    items_value = EXCLUDED.items_value, contract_value = EXCLUDED.contract_value,
    advances_received = EXCLUDED.advances_received,
    cumulative_billed = EXCLUDED.cumulative_billed,
    shipping_address = EXCLUDED.shipping_address,
    shipping_state_code = EXCLUDED.shipping_state_code,
    place_of_supply = EXCLUDED.place_of_supply,
    payment_terms = EXCLUDED.payment_terms, delivery_terms = EXCLUDED.delivery_terms,
    validity = EXCLUDED.validity, remarks = EXCLUDED.remarks,
    e_way_bill = EXCLUDED.e_way_bill, gst_collectable = EXCLUDED.gst_collectable;

INSERT INTO invoice_orders (po_no, po_date, buyer, account, goods, state, items,
    milestones, payments, invoices, freight, freight_in_rate, discount, items_value,
    contract_value, advances_received, cumulative_billed, shipping_address,
    shipping_state_code, place_of_supply, payment_terms, delivery_terms, validity,
    remarks, e_way_bill, gst_collectable)
VALUES (
    'AVL-PO/26-27/SH/003', '2026-06-17', 'LCB',
    'hardware', TRUE, 'SETTLED',
    '[{"description": "IoT Hardware - Microcontroller Sensor Panels", "specs": "ESP32-S3 custom telemetry hardware unit with integrated sensor array and enclosure casing.", "hsn": "8517 62 90", "qty": 8, "uqc": "Nos", "rate": 7000.0}]'::jsonb, '[{"label": "Advance on PO acceptance", "percent": 12, "trigger": "On PO acceptance"}, {"label": "Balance on delivery", "percent": 88, "trigger": "On delivery"}]'::jsonb,
    '[{"date": "2026-06-17", "amount": 6500.0, "mode": "NEFT", "remark": "Advance payment for next 8 sensors - order 2", "invoice_no": "AVL/26-27/SH/005"}, {"date": "2026-07-06", "amount": 49500.0, "mode": "NEFT", "remark": "Balance payment of 8 sensors - order 2", "invoice_no": "AVL/26-27/SH/007"}]'::jsonb, '[{"kind": "ADVANCE", "no": "AVL/26-27/SH/005", "date": "2026-06-17", "amount": 6500.0, "mode": "NEFT", "remark": "Advance payment for next 8 sensors - order 2"}, {"kind": "PARTIAL", "no": "AVL/26-27/SH/007", "date": "2026-07-06", "amount": 49500.0, "mode": "NEFT", "remark": "Balance payment of 8 sensors - order 2"}, {"kind": "FINAL", "no": "AVL/26-27/SH/008", "date": "2026-07-06", "amount": 56000.0, "remark": "Final dispatch/settlement"}, {"kind": "REVISED", "no": "AVL-RV/26-27/SH/002", "date": "2026-08-11", "amount": 56000.0, "remark": "Revised tax invoice replacing AVL/26-27/SH/008"}]'::jsonb,
    0.0, FALSE, 0.0,
    56000.0, 56000.0,
    56000.0, 56000.0,
    '["BioSanjeevni", "Kamdhenu Dham Gaushala, Gurugram", "Haryana"]'::jsonb,
    '06', 'Haryana (06)',
    'Advance on PO acceptance; balance on delivery.', 'Sensors dispatched after advance receipt.',
    'PO valid for 30 days.', 'Order 2 - 8 ESP32-S3 sensor panels. Fully paid via two receipts (17/06/2026 and 06/07/2026).',
    '{"required": true, "generated_by": "buyer"}'::jsonb,
    NULL)
ON CONFLICT (po_no) DO UPDATE SET
    po_date = EXCLUDED.po_date, buyer = EXCLUDED.buyer, account = EXCLUDED.account,
    goods = EXCLUDED.goods, state = EXCLUDED.state, items = EXCLUDED.items,
    milestones = EXCLUDED.milestones, payments = EXCLUDED.payments,
    invoices = EXCLUDED.invoices, freight = EXCLUDED.freight,
    freight_in_rate = EXCLUDED.freight_in_rate, discount = EXCLUDED.discount,
    items_value = EXCLUDED.items_value, contract_value = EXCLUDED.contract_value,
    advances_received = EXCLUDED.advances_received,
    cumulative_billed = EXCLUDED.cumulative_billed,
    shipping_address = EXCLUDED.shipping_address,
    shipping_state_code = EXCLUDED.shipping_state_code,
    place_of_supply = EXCLUDED.place_of_supply,
    payment_terms = EXCLUDED.payment_terms, delivery_terms = EXCLUDED.delivery_terms,
    validity = EXCLUDED.validity, remarks = EXCLUDED.remarks,
    e_way_bill = EXCLUDED.e_way_bill, gst_collectable = EXCLUDED.gst_collectable;

INSERT INTO invoice_orders (po_no, po_date, buyer, account, goods, state, items,
    milestones, payments, invoices, freight, freight_in_rate, discount, items_value,
    contract_value, advances_received, cumulative_billed, shipping_address,
    shipping_state_code, place_of_supply, payment_terms, delivery_terms, validity,
    remarks, e_way_bill, gst_collectable)
VALUES (
    'AVL-PO/26-27/SH/004', '2026-07-06', 'LCB',
    'hardware', TRUE, 'SETTLED',
    '[{"description": "IoT Hardware - Microcontroller Sensor Panels", "specs": "ESP32-S3 custom telemetry hardware unit with integrated sensor array and enclosure casing.", "hsn": "8517 62 90", "qty": 12, "uqc": "Nos", "rate": 7000.0}]'::jsonb, '[{"label": "Advance on PO acceptance", "percent": 1, "trigger": "On PO acceptance"}, {"label": "Interim payment", "percent": 24, "trigger": "On 18/07/2026"}, {"label": "Balance on delivery", "percent": 76, "trigger": "On delivery"}]'::jsonb,
    '[{"date": "2026-07-06", "amount": 500.0, "mode": "NEFT", "remark": "Advance payment of 12 sensors - order 3", "invoice_no": "AVL/26-27/SH/009"}, {"date": "2026-07-18", "amount": 20000.0, "mode": "NEFT", "remark": "Balance payment of 12 sensors advance", "invoice_no": "AVL/26-27/SH/010"}, {"date": "2026-07-28", "amount": 63500.0, "mode": "NEFT", "remark": "Balance payment of 12 sensors", "invoice_no": "AVL/26-27/SH/011"}]'::jsonb, '[{"kind": "ADVANCE", "no": "AVL/26-27/SH/009", "date": "2026-07-06", "amount": 500.0, "mode": "NEFT", "remark": "Advance payment of 12 sensors - order 3"}, {"kind": "PARTIAL", "no": "AVL/26-27/SH/010", "date": "2026-07-18", "amount": 20000.0, "mode": "NEFT", "remark": "Balance payment of 12 sensors advance"}, {"kind": "PARTIAL", "no": "AVL/26-27/SH/011", "date": "2026-07-28", "amount": 63500.0, "mode": "NEFT", "remark": "Balance payment of 12 sensors"}, {"kind": "FINAL", "no": "AVL/26-27/SH/012", "date": "2026-07-28", "amount": 84000.0, "remark": "Final dispatch/settlement"}, {"kind": "REVISED", "no": "AVL-RV/26-27/SH/003", "date": "2026-08-11", "amount": 84000.0, "remark": "Revised tax invoice replacing AVL/26-27/SH/012"}]'::jsonb,
    0.0, FALSE, 0.0,
    84000.0, 84000.0,
    84000.0, 84000.0,
    '["LCB Fertilizers Pvt. Ltd.", "Kushinagar Plant", "Kushinagar, Uttar Pradesh"]'::jsonb,
    '09', 'Uttar Pradesh (09)',
    'Advance on PO acceptance; balance on delivery.', 'Sensors dispatched after advance receipt.',
    'PO valid for 30 days.', 'Order 3 - 12 ESP32-S3 sensor panels. Fully paid via three receipts (06/07, 18/07 and 28/07/2026).',
    '{"required": true, "generated_by": "buyer"}'::jsonb,
    NULL)
ON CONFLICT (po_no) DO UPDATE SET
    po_date = EXCLUDED.po_date, buyer = EXCLUDED.buyer, account = EXCLUDED.account,
    goods = EXCLUDED.goods, state = EXCLUDED.state, items = EXCLUDED.items,
    milestones = EXCLUDED.milestones, payments = EXCLUDED.payments,
    invoices = EXCLUDED.invoices, freight = EXCLUDED.freight,
    freight_in_rate = EXCLUDED.freight_in_rate, discount = EXCLUDED.discount,
    items_value = EXCLUDED.items_value, contract_value = EXCLUDED.contract_value,
    advances_received = EXCLUDED.advances_received,
    cumulative_billed = EXCLUDED.cumulative_billed,
    shipping_address = EXCLUDED.shipping_address,
    shipping_state_code = EXCLUDED.shipping_state_code,
    place_of_supply = EXCLUDED.place_of_supply,
    payment_terms = EXCLUDED.payment_terms, delivery_terms = EXCLUDED.delivery_terms,
    validity = EXCLUDED.validity, remarks = EXCLUDED.remarks,
    e_way_bill = EXCLUDED.e_way_bill, gst_collectable = EXCLUDED.gst_collectable;

INSERT INTO invoice_orders (po_no, po_date, buyer, account, goods, state, items,
    milestones, payments, invoices, freight, freight_in_rate, discount, items_value,
    contract_value, advances_received, cumulative_billed, shipping_address,
    shipping_state_code, place_of_supply, payment_terms, delivery_terms, validity,
    remarks, e_way_bill, gst_collectable)
VALUES (
    'AVL-PO/26-27/SH/005', '2026-07-28', 'LCB',
    'hardware', TRUE, 'SETTLED',
    '[{"description": "IoT Hardware - Microcontroller Sensor Panels", "specs": "ESP32-S3 custom telemetry hardware unit with integrated sensor array and enclosure casing.", "hsn": "8517 62 90", "qty": 4, "uqc": "Nos", "rate": 7000.0}]'::jsonb, '[{"label": "Advance on PO acceptance", "percent": 5, "trigger": "On PO acceptance"}, {"label": "Balance on delivery", "percent": 95, "trigger": "On delivery"}]'::jsonb,
    '[{"date": "2026-07-28", "amount": 1500.0, "mode": "NEFT", "remark": "Advance of 4 sensors - order 4", "invoice_no": "AVL/26-27/SH/013"}, {"date": "2026-08-11", "amount": 26500.0, "mode": "NEFT", "remark": "Balance payment of 4 sensors - order 4", "invoice_no": "AVL/26-27/SH/014"}]'::jsonb, '[{"kind": "ADVANCE", "no": "AVL/26-27/SH/013", "date": "2026-07-28", "amount": 1500.0, "mode": "NEFT", "remark": "Advance of 4 sensors - order 4"}, {"kind": "REVISED", "no": "AVL-RV/26-27/SH/004", "date": "2026-08-11", "amount": 28000.0, "remark": "Revised tax invoice replacing AVL/26-27/SH/013"}, {"kind": "PARTIAL", "no": "AVL/26-27/SH/014", "date": "2026-08-11", "amount": 26500.0, "mode": "NEFT", "remark": "Balance payment of 4 sensors - order 4"}]'::jsonb,
    0.0, FALSE, 0.0,
    28000.0, 28000.0,
    28000.0, 28000.0,
    '["BioSanjeevni", "Yamuna Nagar Plant", "Yamuna Nagar, Haryana"]'::jsonb,
    '06', 'Haryana (06)',
    'Advance on PO acceptance; balance on delivery.', 'Sensors dispatched after advance receipt.',
    'PO valid for 30 days.', 'Order 4 - 4 ESP32-S3 sensor panels. Fully paid: advance of INR 1,500 received on 28/07/2026 and balance of INR 26,500 received on 11/08/2026.',
    NULL,
    NULL)
ON CONFLICT (po_no) DO UPDATE SET
    po_date = EXCLUDED.po_date, buyer = EXCLUDED.buyer, account = EXCLUDED.account,
    goods = EXCLUDED.goods, state = EXCLUDED.state, items = EXCLUDED.items,
    milestones = EXCLUDED.milestones, payments = EXCLUDED.payments,
    invoices = EXCLUDED.invoices, freight = EXCLUDED.freight,
    freight_in_rate = EXCLUDED.freight_in_rate, discount = EXCLUDED.discount,
    items_value = EXCLUDED.items_value, contract_value = EXCLUDED.contract_value,
    advances_received = EXCLUDED.advances_received,
    cumulative_billed = EXCLUDED.cumulative_billed,
    shipping_address = EXCLUDED.shipping_address,
    shipping_state_code = EXCLUDED.shipping_state_code,
    place_of_supply = EXCLUDED.place_of_supply,
    payment_terms = EXCLUDED.payment_terms, delivery_terms = EXCLUDED.delivery_terms,
    validity = EXCLUDED.validity, remarks = EXCLUDED.remarks,
    e_way_bill = EXCLUDED.e_way_bill, gst_collectable = EXCLUDED.gst_collectable;

INSERT INTO invoice_transactions (s_no, date, amount, remarks, bank_ref,
    allocations, combined_invoice)
VALUES (
    11, '2026-05-13', 38000.0,
    'Transportation cost - 10,500 + advance payment of 8 sensors', 'NEFT-HDFCH00994747262-0001HDFC4CFA187F06ED',
    '[{"invoice_no": "AVL/26-27/SH/001", "amount": 27500.0, "order": "AVL-PO/26-27/SH/001"}, {"invoice_no": "AVL/26-27/SH/002", "amount": 10500.0, "order": "AVL-PO/26-27/SH/002"}]'::jsonb, 'AVL-CMB/26-27/001')
ON CONFLICT (s_no) DO UPDATE SET
    date = EXCLUDED.date, amount = EXCLUDED.amount, remarks = EXCLUDED.remarks,
    bank_ref = EXCLUDED.bank_ref, allocations = EXCLUDED.allocations,
    combined_invoice = EXCLUDED.combined_invoice;

INSERT INTO invoice_transactions (s_no, date, amount, remarks, bank_ref,
    allocations, combined_invoice)
VALUES (
    67, '2026-06-17', 35000.0,
    'Balance payment for sensors + advance payment for next 8 sensors', 'NEFT-HDFCH01068749667-0001HDFCE5ED0B05042F',
    '[{"invoice_no": "AVL/26-27/SH/003", "amount": 28500.0, "order": "AVL-PO/26-27/SH/001"}, {"invoice_no": "AVL/26-27/SH/005", "amount": 6500.0, "order": "AVL-PO/26-27/SH/003"}]'::jsonb, 'AVL-CMB/26-27/002')
ON CONFLICT (s_no) DO UPDATE SET
    date = EXCLUDED.date, amount = EXCLUDED.amount, remarks = EXCLUDED.remarks,
    bank_ref = EXCLUDED.bank_ref, allocations = EXCLUDED.allocations,
    combined_invoice = EXCLUDED.combined_invoice;

INSERT INTO invoice_transactions (s_no, date, amount, remarks, bank_ref,
    allocations, combined_invoice)
VALUES (
    79, '2026-06-20', 50000.0,
    'Advance payment for transport cost - fertilizer first payment (F1)', 'NEFT-HDFCH01072839753-0001HDFC6BBAC4AB8823',
    '[{"invoice_no": "AVL/26-27/FER/001", "amount": 50000.0, "order": "AVL-PO/26-27/FER/001"}]'::jsonb, NULL)
ON CONFLICT (s_no) DO UPDATE SET
    date = EXCLUDED.date, amount = EXCLUDED.amount, remarks = EXCLUDED.remarks,
    bank_ref = EXCLUDED.bank_ref, allocations = EXCLUDED.allocations,
    combined_invoice = EXCLUDED.combined_invoice;

INSERT INTO invoice_transactions (s_no, date, amount, remarks, bank_ref,
    allocations, combined_invoice)
VALUES (
    121, '2026-07-06', 50000.0,
    'Advance/balance payment for 8 sensors - advance payment of 12 sensors', 'NEFT-HDFCH01108057747-0001SENSORS',
    '[{"invoice_no": "AVL/26-27/SH/007", "amount": 49500.0, "order": "AVL-PO/26-27/SH/003"}, {"invoice_no": "AVL/26-27/SH/009", "amount": 500.0, "order": "AVL-PO/26-27/SH/004"}]'::jsonb, 'AVL-CMB/26-27/003')
ON CONFLICT (s_no) DO UPDATE SET
    date = EXCLUDED.date, amount = EXCLUDED.amount, remarks = EXCLUDED.remarks,
    bank_ref = EXCLUDED.bank_ref, allocations = EXCLUDED.allocations,
    combined_invoice = EXCLUDED.combined_invoice;

INSERT INTO invoice_transactions (s_no, date, amount, remarks, bank_ref,
    allocations, combined_invoice)
VALUES (
    150, '2026-07-09', 100000.0,
    'Fertilizer partial payment (F2)', 'NEFT-HDFCH01118690525-0001GMR',
    '[{"invoice_no": "AVL/26-27/FER/002", "amount": 100000.0, "order": "AVL-PO/26-27/FER/001"}]'::jsonb, NULL)
ON CONFLICT (s_no) DO UPDATE SET
    date = EXCLUDED.date, amount = EXCLUDED.amount, remarks = EXCLUDED.remarks,
    bank_ref = EXCLUDED.bank_ref, allocations = EXCLUDED.allocations,
    combined_invoice = EXCLUDED.combined_invoice;

INSERT INTO invoice_transactions (s_no, date, amount, remarks, bank_ref,
    allocations, combined_invoice)
VALUES (
    171, '2026-07-15', 50000.0,
    'Fertilizer partial payment (F3)', 'NEFT-HDFCH01128822714-0001PENDING SUPPLY',
    '[{"invoice_no": "AVL/26-27/FER/003", "amount": 50000.0, "order": "AVL-PO/26-27/FER/001"}]'::jsonb, NULL)
ON CONFLICT (s_no) DO UPDATE SET
    date = EXCLUDED.date, amount = EXCLUDED.amount, remarks = EXCLUDED.remarks,
    bank_ref = EXCLUDED.bank_ref, allocations = EXCLUDED.allocations,
    combined_invoice = EXCLUDED.combined_invoice;

INSERT INTO invoice_transactions (s_no, date, amount, remarks, bank_ref,
    allocations, combined_invoice)
VALUES (
    183, '2026-07-16', 50000.0,
    'Fertilizer partial payment (F4) - Ashutosh', 'NEFT-HDFCH01131865188-0001PAYMENT FERTILIZ',
    '[{"invoice_no": "AVL/26-27/FER/004", "amount": 50000.0, "order": "AVL-PO/26-27/FER/001"}]'::jsonb, NULL)
ON CONFLICT (s_no) DO UPDATE SET
    date = EXCLUDED.date, amount = EXCLUDED.amount, remarks = EXCLUDED.remarks,
    bank_ref = EXCLUDED.bank_ref, allocations = EXCLUDED.allocations,
    combined_invoice = EXCLUDED.combined_invoice;

INSERT INTO invoice_transactions (s_no, date, amount, remarks, bank_ref,
    allocations, combined_invoice)
VALUES (
    197, '2026-07-18', 20000.0,
    'Sensor cost - balance payment of 12 sensors advance', 'NEFT-HDFCH01135248562-0001SENSORS',
    '[{"invoice_no": "AVL/26-27/SH/010", "amount": 20000.0, "order": "AVL-PO/26-27/SH/004"}]'::jsonb, NULL)
ON CONFLICT (s_no) DO UPDATE SET
    date = EXCLUDED.date, amount = EXCLUDED.amount, remarks = EXCLUDED.remarks,
    bank_ref = EXCLUDED.bank_ref, allocations = EXCLUDED.allocations,
    combined_invoice = EXCLUDED.combined_invoice;

INSERT INTO invoice_transactions (s_no, date, amount, remarks, bank_ref,
    allocations, combined_invoice)
VALUES (
    237, '2026-07-28', 65000.0,
    'Balance payment of 12 sensors - advance of 4 sensors', 'NEFT-HDFCH01153023568-0001FERTILIZER',
    '[{"invoice_no": "AVL/26-27/SH/011", "amount": 63500.0, "order": "AVL-PO/26-27/SH/004"}, {"invoice_no": "AVL/26-27/SH/013", "amount": 1500.0, "order": "AVL-PO/26-27/SH/005"}]'::jsonb, 'AVL-CMB/26-27/004')
ON CONFLICT (s_no) DO UPDATE SET
    date = EXCLUDED.date, amount = EXCLUDED.amount, remarks = EXCLUDED.remarks,
    bank_ref = EXCLUDED.bank_ref, allocations = EXCLUDED.allocations,
    combined_invoice = EXCLUDED.combined_invoice;

INSERT INTO invoice_transactions (s_no, date, amount, remarks, bank_ref,
    allocations, combined_invoice)
VALUES (
    238, '2026-08-11', 30000.0,
    'Balance payment of 4 sensors - advance for balance of fertiliser supply', 'NEFT-20260811-30000-SENSORS-FERTILIZER',
    '[{"invoice_no": "AVL/26-27/SH/014", "amount": 26500.0, "order": "AVL-PO/26-27/SH/005"}, {"invoice_no": "AVL/26-27/FER/005", "amount": 3500.0, "order": "AVL-PO/26-27/FER/001"}]'::jsonb, 'AVL-CMB/26-27/005')
ON CONFLICT (s_no) DO UPDATE SET
    date = EXCLUDED.date, amount = EXCLUDED.amount, remarks = EXCLUDED.remarks,
    bank_ref = EXCLUDED.bank_ref, allocations = EXCLUDED.allocations,
    combined_invoice = EXCLUDED.combined_invoice;

